services:
  bayzat-be-engineering-assignment:
    image: aweperi/bayzat-be-engineering-assignment
    depends_on:
      - local-mysql-database
    ports:
      - 8888:8888
  local-mysql-database:
    image: mysql/mysql-server:8.0
    container_name: local-mysql-database
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bayzatbe