server:
  port: 5000
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
jwt-security:
  secret: PseudoSecret-Pseudosecret-BAYZAT-Backend-Eng-Assignement-PseudoSecret-Pseudosecret
  expiration-time: 365


spring:
  application:
    name: bazyatbeengineeringassignment
  jpa:
    defer-datasource-initialization: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update
      use-new-id-generator-mappings: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true
    properties:
      hibernate.show_sql: false
      hibernate.dialect.storage_engine: innodb
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/bayzatbe?ssl-mode=REQUIRED
  sql:
    init:
      mode: always
      continue-on-error: true
      data-locations: classpath:db/V2__data.sql
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: false
    out-of-order: true
    locations: classpath:db/migration
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
---
spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://host.docker.internal:3306/bauyzatbe?ssl-mode=REQUIRED
  config:
    activate:
      on-profile: docker
server:
  port: 8888
  servlet:
    context-path: /starter-test