server:
  port: 5000
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never


spring:
  application:
    name: bazyatbeengineeringassignment
  datasource:
    username: 'root'
    url: jdbc:mysql://localhost:3306/bayzatbe?useSSL=false
    password: 'root'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    database-platform:
    open-in-view: false
    defer-datasource-initialization: false
  sql:
    init:
      mode: ALWAYS
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: false
    out-of-order: true
    locations: classpath:db/migration