server:
  port: 5000
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never


spring:
  application:
    name: bazyatbeengineeringassignment
  datasource:
    username: 'postgres'
    url: jdbc:postgresql://localhost:5432/bayzatbe
    password: 'postgres'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: none
    database-platform:
    open-in-view: false
    defer-datasource-initialization: false
    generate-ddl: false
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: false
    out-of-order: true
    locations: classpath:db/migration