server:
  port: 5000
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
jwt-security:
  secret: PseudoSecret-Pseudosecret-MY-OWN-JWT-SECRET-KEY-PseudoSecret-Pseudosecret
  expiration-time: 365


spring:
  application:
    name: bazyatbeengineeringassignment
  jpa:
    defer-datasource-initialization: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update
      use-new-id-generator-mappings: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
      #    database-platform: org.hibernate.dialect.MySQL57Dialect
    open-in-view: true
    properties:
      hibernate.show_sql: false
      hibernate.dialect.storage_engine: innodb
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/bayzatbe?ssl-mode=REQUIRED
      #    url: jdbc:mysql://localhost:3306/starterspringkotlin?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
  sql:
    init:
      mode: always
      continue-on-error: true
      data-locations: classpath:db/data.sql
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE