server:
  port: 5000
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never


spring:
  application:
    name: bazyatbeengineeringassignment
  datasource:
    username: 'postgres'
    url: jdbc:postgresql://localhost:5432/bayzatbe
    password: 'postgres'
  output:
      ansi:
        enabled: ALWAYS
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: false
    out-of-order: true
    locations: classpath:db/migration
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE